.TH execdir 1 "2022-07-13" "execdir"

.SH NAME
execdir \- execute a command in a specific directory 

.SH SYNOPSIS
\fBexecdir\fR [\fB-h\fR] [\fB-v\fR] [\fB-p\fR] [\fB-a\fR]  [\fB-s\fR] [\fB-n\fR \fINAME\fR \fIPATH\fR] [\fB-g\fR \fINAME\fR] [\fB-r\fR \fINAME\fR] [\fB-l\fR] [\fIARGS\fR...]

.SH DESCRIPTION
\fBexecdir\fR is a tool that lets you run a command in a specific directory. It supports shell commands and path aliases. \fBexecdir\fR will try to get an alias if path doesn't exist.

There is also a symlink called \fBx\fR, so you can type less using it.

.SH OPTIONS

.IP "\fB-h\fR"
Display the help message and exit

.IP "\fB-v\fR"
Display the version number of execdir and exit

.IP "\fB-s\fR"
Execute the command as a shell command

.IP "\fB-n\fR \fINAME\fR \fIPATH\fR"
Create an alias for a path

.IP "\fB-r\fR \fINAME\fR"
Delete an alias

.IP "\fB-g\fR \fINAME\fR"
Get an alias

.IP "\fB-l\fR"
List all aliases

.IP "\fB-a\fR"
Use alias

.IP "\fB-p\fR"
Create new directories

.SH EXECDIR FILE

All aliases are defined in the \fB~/.execdir.db\fR file. This is an Berkeley Database file, on which each key is an alias, and value is an path

.SH AUTHOR
Gustavo Costa <xfgusta@gmail.com> (Original author)
qr243vbi - new author

.SH BUGS
Report bugs to <https://github.com/qr243vbi/execdir/issues>

.SH COPYRIGHT
Copyright (c) 2022 Gustavo Costa
Copyright (c) 2025 qr243vbi
